### ISSUE TITLE
tanium_nlp.py errors

### ISSUE THREAD

**Issue by djmundus** [tanium/SplunkforTanium#10]
I'm trying to run Tanium queries from Splunk using the tanium_nlp.py script.  I've tried running it using the python embedded in Splunk, and I get the following errors:

/opt/splunk/bin/splunk cmd python /opt/splunk/etc/apps/tanium/bin/tanium_nlp.py --tanium "10.10.10.10" --user "Tanium" --password "Tanium" --question "Get Computer Name and Running Processes from all machines" --timeout "10"
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 373, in <module>
    main()
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 335, in main
    xml_response = my_tanium.ask_tanium_a_question(question,timeout)
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 255, in ask_tanium_a_question
    self.last_id = self.send_request_to_tanium (sensors)
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 248, in send_request_to_tanium
    id_num = id_num.group(2)

I get the same error using the "script" command in the Splunk GUI.

If I run the same command just using the python version in OEL, I get the following:

Traceback (most recent call last):
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 373, in <module>
    main()
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 335, in main
    xml_response = my_tanium.ask_tanium_a_question(question,timeout)
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 255, in ask_tanium_a_question
    self.last_id = self.send_request_to_tanium (sensors)
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 231, in send_request_to_tanium
    guess_xml = self.make_soap_connection (soap_message)
  File "/opt/splunk/etc/apps/tanium/bin/tanium_nlp.py", line 73, in make_soap_connection
    webservice.endheaders()
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1236, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

All of the other scripts work from both the command line and Splunk search pipeline.

**Comment by JCobeyTanium** [comment]
The code needs to be updated to deal with the ssl/tls certs. Since using the nlp search via Splunk feature is has been removed, Ill close this.
